<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>AutoClicker</AssemblyName>
    <RootNamespace>AutoClicker</RootNamespace>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>Assets\AutoClickerIcon.ico</ApplicationIcon>
    <Authors>JBX7</Authors>
    <Copyright>Copyright © 2026 JBX7</Copyright>
    <Version>1.1.0</Version>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="MainForm.cs" />
    <Compile Remove="AutoClicker.Tests\**\*.cs" />
    <Compile Remove="AutoClicker.Benchmarks\**\*.cs" />
  </ItemGroup>
  <ItemGroup>
    <Using Remove="System.Drawing" />
    <Using Remove="System.Windows.Forms" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Assets\AutoClickerIcon.ico" />
    <Resource Include="Assets\AutoClickerRunningIcon.ico" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="OpenRGB.NET" Version="3.1.1" />
  </ItemGroup>
</Project>
